---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: database-connection
  namespace: admin-api
spec:
  encryptedData:
    db: AgBjinbczdIlN56ikX0K5uyUPfO/5mVq3K6rC0GytLFgepM4cZ5dGNJQu0Wlj4Jb1ogdGN0M9qui3/q9pKncYk2zHrdLCNe9Tr8Remr2TZI1XX+ck3qeyiVhm424XcQF1dtbJSAjgma77K/uLMEigr/HVATrDsVqsv8aIOL0AZGcUJhv/b5QthOSrG9n13+yF+JNu6BbiPEFjxkzAPid0jkaX0O10Dk/ZfiKvb8dt4J7HCebpS1MezVmsCvfY368KU0gUXMENivIEkf+w5HNyF847kF9MPVYJea4iwyOE5hcnCvcMkW+IAaBh5XFuy5VEEjYvYK+0wc8qrByW7EZ7uYy4l9RzvkUJlMahunX3Nq5hTJkGmz7ogLsymP3VNcG6zVQ5/W5Ux/4PqJcuWYi8kkBx4egXuYxtxnSeIpAwA6gAIXbxLCdiJ0wLjTOoicXKBXrsxmK+bbRqaA49FMwwCzbbYiTnZKHO7gbAFUw/32rxeS7wy9NzsVNe+HKEZPh31mFbA6aQHznjR53BbCD3QZf4x6YtpoQBCdo2EZNQxWh432VX2jYme1cNKvwW/GZlUSRUds8QW1xMGQAFSt7/8qioH+RmIgpByFf//7A8bbFtycbE1mYe0x5m84zPK+pxd6P1T1Xny/Mqi1g+H9mR01adX3J5F2Y6/9DtUuMvNQoQVD0bjnUcIcg6gRfH9297DWoCxtzsA9mQnJhSxpLADhlNBVeQE4MoiESfAvX3Q/qYfFp9W3Gn6H6VWoav244VVKN+PcxoIpRsuzlGi43gFXdCBVLC02Ny29Ehn3eCGcaVS1Ned8NjN1CvijMmCJd85wUURmXck6O4ko8gYIh8ZYnXfzRi0xw6VW9TNhkPZcAiU6GUWxUX1rB3OvwcO3ngh0=
  template:
    metadata:
      name: database-connection
      namespace: admin-api
