/*
 * To test organizational user, like login, permission, and so on
 */
import {ApplicationConfig, ExpressServer} from '../../server';

const request = require("supertest");
const seed = require("../../tests/seed/seed.ts");

console.log(seed.description);

describe("Integration", () => {
  let server;

  beforeAll(async () => {
    await seed.clear();
    await seed.seed();
    const config = {
      rest: {
        port: +(process.env.NODE_PORT || 3000),
        host: process.env.HOST || 'localhost',
        openApiSpec: {
          // useful when used with OpenAPI-to-GraphQL to locate your application
          setServersFromRequest: true,
        },
        // Use the LB4 application as a route. It should not be listening.
        listenOnStart: false,
      },
      //hack the root dir to let Loopback load the ./dict though it's not 
      //generated by Jest (by tsc though)
      projectRoot: __dirname + "/../../../dist",
    };
    server = new ExpressServer(config);
    await server.boot();
    await server.lbApp.start();
  });

  afterAll(async () => {
    await seed.clear();
  });


  it("can login with default account admin:admin", async () => {
    const response = await request(server.app)
      .post("/auth/login")
      .send({
        userName: "admin",
        password: "admin",
      });
    expect(response.statusCode).toBe(200);
  });

  

  describe(`Login with account ${seed.users.test.username}`, () => {
    let token;

    beforeEach(async () => {
      const response = await request(server.app)
        .post("/auth/login")
        .send({
          userName: seed.users.test.username,
          password: seed.users.test.password,
        });
      expect(response.statusCode).toBe(200);
      expect(response.body.token).toBeDefined();
      token = response.body.token;
    });

    it("shoulbe be able request /api/trees/count, and get 5 trees", async () => {
      const response = await request(server.app)
        .get("/api/trees/count?filter[offset]=0&filter[limit]=100&filter[skip]=0")
        .set('Authorization', token);
      expect(response.statusCode).toBe(200);
      expect(response.body).toMatchObject({
        count: 5,
      });
    });

    it("shoulbe be able request /api/trees, and get 5 trees", async () => {
      const response = await request(server.app)
        .get("/api/trees?filter[offset]=0&filter[limit]=100&filter[skip]=0")
        .set('Authorization', token);
      expect(response.statusCode).toBe(200);
      expect(response.body).toBeInstanceOf(Array)
      expect(response.body).toHaveLength(5);
    });

    it("shoulbe not be able to request /api/planters", async () => {
      const response = await request(server.app)
        .get("/api/planter/count")
        .set('Authorization', token);
      expect(response.statusCode).toBe(401);
    });

  });


  describe(`can login with organization account ${seed.users.freetown.username}`, () => {
    let token;

    beforeAll(async () => {
      const response = await request(server.app)
        .post("/auth/login")
        .send({
          userName: seed.users.freetown.username,
          password: seed.users.freetown.password,
        });
      expect(response.statusCode).toBe(200);
      expect(response.body).toMatchObject({
        token: expect.any(String),
        user: {
          policy: {
            organization: {
              name: expect.any(String),
              id: expect.any(Number),
            },
            policies: expect.any(Array),
          },
        },
      });
      token = response.body.token;
    });

    describe("API trees", () => {
      it("Should not be able to request /api/trees", async () => {
        const response = await request(server.app)
          .get("/api/trees?")
          .set('Authorization', token);
        expect(response.statusCode).toBe(401);
      });

      it(`Should be able to request /api/organization/${seed.roles.freetownManager.policy.organization.id}/trees and get 3 trees`, async () => {
        const response = await request(server.app)
          .get(`/api/organization/${seed.roles.freetownManager.policy.organization.id}/trees?filter[offset]=0&filter[limit]=100&filter[skip]=0`)
          .set('Authorization', token);
        expect(response.statusCode).toBe(200);
        expect(response.body).toHaveLength(3);
      });

      it(`shoulbe be able request /api/organization/${seed.roles.freetownManager.policy.organization.id}/trees/count, and get 3 trees`, async () => {
        const response = await request(server.app)
          .get(`/api/organization/${seed.roles.freetownManager.policy.organization.id}/trees/count?filter[offset]=0&filter[limit]=100&filter[skip]=0`)
          .set('Authorization', token);
        expect(response.statusCode).toBe(200);
        expect(response.body).toMatchObject({
          count: 3
        });
      });


      it(`Should be able to request /api/organization/${seed.roles.freetownManager.policy.organization.id}/trees/3 ,cuz this tree belong to this organization`, async () => {
        const response = await request(server.app)
          .get(`/api/organization/${seed.roles.freetownManager.policy.organization.id}/trees/3`)
          .set('Authorization', token);
        expect(response.statusCode).toBe(200);
        expect(response.body).toMatchObject({
          id: 3,
        });
      });

      it(`Should be able to PATCH /api/organization/${seed.roles.freetownManager.policy.organization.id}/trees/3 `, async () => {
        const response = await request(server.app)
          .patch(`/api/organization/${seed.roles.freetownManager.policy.organization.id}/trees/3`)
          .set('Authorization', token)
          .send({
            active: false,
          });
        expect(response.statusCode).toBe(204);
        expect(response.body).toMatchObject({
        });
      });

      it(`Should be able to request /api/organization/${seed.roles.freetownManager.policy.organization.id}/trees/5 ,cuz this tree belong to this organization`, async () => {
        const response = await request(server.app)
          .get(`/api/organization/${seed.roles.freetownManager.policy.organization.id}/trees/5`)
          .set('Authorization', token);
        expect(response.statusCode).toBe(200);
        expect(response.body).toMatchObject({
          id: 5,
        });
      });

      it(`Should be able to PATCH /api/organization/${seed.roles.freetownManager.policy.organization.id}/trees/5 `, async () => {
        const response = await request(server.app)
          .patch(`/api/organization/${seed.roles.freetownManager.policy.organization.id}/trees/5`)
          .set('Authorization', token)
          .send({
            active: false,
          });
        expect(response.statusCode).toBe(204);
        expect(response.body).toMatchObject({
        });
      });

      it(`Should not be able to request /api/organization/${seed.roles.freetownManager.policy.organization.id}/trees/1 ,cuz this tree doesn't belong to this organization`, async () => {
        const response = await request(server.app)
          .get(`/api/organization/${seed.roles.freetownManager.policy.organization.id}/trees/1`)
          .set('Authorization', token);
        expect(response.statusCode).toBe(401);
      });

      it(`Should not be able to PATCH /api/organization/${seed.roles.freetownManager.policy.organization.id}/trees/1 `, async () => {
        const response = await request(server.app)
          .patch(`/api/organization/${seed.roles.freetownManager.policy.organization.id}/trees/1`)
          .set('Authorization', token)
          .send({
            active: false,
          });
        expect(response.statusCode).toBe(401);
      });
    });

    describe("API planter", () => {
      it("Should not be able to request /api/planter", async () => {
        const response = await request(server.app)
          .get("/api/planter?")
          .set('Authorization', token);
        expect(response.statusCode).toBe(401);
      });

      it(`Should be able to request /api/organization/${seed.roles.freetownManager.policy.organization.id}/planter and get 1 planter`, async () => {
        const response = await request(server.app)
          .get(`/api/organization/${seed.roles.freetownManager.policy.organization.id}/planter?filter[offset]=0&filter[limit]=100&filter[skip]=0`)
          .set('Authorization', token);
        expect(response.statusCode).toBe(200);
        expect(response.body).toHaveLength(1);
      });

      it(`shoulbe be able request /api/organization/${seed.roles.freetownManager.policy.organization.id}/planter/count, and get 1 planter`, async () => {
        const response = await request(server.app)
          .get(`/api/organization/${seed.roles.freetownManager.policy.organization.id}/planter/count?filter[offset]=0&filter[limit]=100&filter[skip]=0`)
          .set('Authorization', token);
        expect(response.statusCode).toBe(200);
        expect(response.body).toMatchObject({
          count: 1
        });
      });


      it(`Should be able to request /api/organization/${seed.roles.freetownManager.policy.organization.id}/planter/1 ,cuz this planter belong to this organization`, async () => {
        const response = await request(server.app)
          .get(`/api/organization/${seed.roles.freetownManager.policy.organization.id}/planter/1`)
          .set('Authorization', token);
        expect(response.statusCode).toBe(200);
        expect(response.body).toMatchObject({
          id: 1,
        });
      });

//      it.only(`Should be able to PATCH /api/organization/${seed.roles.freetownManager.policy.organization.id}/planter/1 `, async () => {
//        const response = await request(server.app)
//          .patch(`/api/organization/${seed.roles.freetownManager.policy.organization.id}/planter/1`)
//          .set('Authorization', token)
//          .send({
//            email: "",
//          });
//        expect(response.statusCode).toBe(204);
//        expect(response.body).toMatchObject({
//        });
//      });

      it(`Should not be able to request /api/organization/${seed.roles.freetownManager.policy.organization.id}/planter/2 ,cuz this planter doesn't belong to this organization`, async () => {
        const response = await request(server.app)
          .get(`/api/organization/${seed.roles.freetownManager.policy.organization.id}/planter/2`)
          .set('Authorization', token);
        expect(response.statusCode).toBe(401);
      });

//      it.only(`Should not be able to PATCH /api/organization/${seed.roles.freetownManager.policy.organization.id}/planter/2 `, async () => {
//        const response = await request(server.app)
//          .patch(`/api/organization/${seed.roles.freetownManager.policy.organization.id}/planter/2`)
//          .set('Authorization', token)
//          .send({
//          });
//        expect(response.statusCode).toBe(401);
//      });
    });



  });


});

