export enum ErrorCode {
  ORGANIZATION_ROLE_ALREADY_ASSIGNED = 'ORGANIZATION_ROLE_ALREADY_ASSIGNED',
  ORGANIZATION_ROLE_ASSIGNMENT_FAILED = 'ORGANIZATION_ROLE_ASSIGNMENT_FAILED',
  ORGANIZATION_CLAIM_UPDATE_FAILED = 'ORGANIZATION_CLAIM_UPDATE_FAILED',
}
