apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-client-secret
  namespace: admin-api
spec:
  encryptedData:
    client-secret: AgAqlxjAPMN6sI1XqmPmFghji2QiA3IjXvmwvdsOO4tDe1tQJTbWkqYNFoQdSuzRGZkrPHBsbERAMH7nDIXH/Aq5+vX9gEqEgGv/AzBSnqg7TGcoG+BN30M+u+u5TE9R3Oi5fa5TGzPCQdpm9Oba/MUoiipy1wTqnPB7Y0RnWdN+ukTn6tu0pHfpCvibYIoskQ5hF4J+1l396isbeTxBjTk2vxC6KRk/MiwqHZ/neK5Xzf3emkrwnsgGrF8og+lj4Wiv+rqWNhKWXN72e7J7mNdC5hTtB+t9+eyOEpI8Q0pJU4s41NnSAkq9mUxOYPaPTAqOmvCcwR9ce+7EOoyD5bz9ZLiar22s3eoBQsOU6jtwW1Z/jPC2ypSy1cLXb/KJkb44xDWC22IpBKhiUejWCgvl3K+PwExUYcPziCAQ/FoKzL0BrikSui9ySiR6VpUVM2/FFylJR9gYF7qtzVFO+17EGrzAMsrR27yItVCggrG5PRAXCjbKj70gUsPMWLpqs6mWXkJqjqrmaPfK7iX/iUxfC4OApTVZmMf9t3GalXY9J1GzGgbG/Eo/Mh41EhylT8giy0KHld/SQyG28xA8yghqRU+pmSwI+M50U3kpy9U82OfWuw1N7Uo2oUMdpWBijot5dr85nXv2wYNNMsfneeGJnzVNasY4FdfGttDgf3+bV/6RQDlSTv8OiGkTIcdwX547ykye/Vh8kmZAZcn3/Mr5sjS9L8LrzKz2WlFSh0uobw==
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-client-secret
      namespace: admin-api
