apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- treetracker-admin-api-deployment.yaml
- treetracker-admin-api-service.yaml
- treetracker-admin-api-mapping.yaml
- keycloak-client-sealed-secret.yaml

images:
- name: greenstand/treetracker-admin-api
  newTag: keycloak-0ef9ab4
