name: Deploy Admin API to Prod Env

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'git-tag'
        required: true

env:
  project-directory: ./

jobs:
  deploy-test:
    name: Deploy latest to prod environment, requires approval
    runs-on: ubuntu-latest
    if: |
      github.repository == "Greenstand/${{ github.event.repository.name }}"
    steps:
      - uses: actions/checkout@v2
      - name: Install kustomize
        run: curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
      - name: Run kustomize
        run: (cd deployment/overlays/production && ../../../kustomize edit set image greenstand/treetracker-admin-api:${{ github.event.inputs.environment }})
      - name: Commit production kustomization file with new app version
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "chore: bump docker image tag ${{ steps.export_bumped_version.outputs.bumped_version }} [skip ci]"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
